version: '3.8'
services:
  server: 
    container_name: spbsrv
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
    env_file: .env.local
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    ports: 
      - 4005:4005
volumes:
  postgres:
    driver: local