version: '3.8'
services:
  nginx:
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - proxy
    depends_on:
      - server
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: spbdb00
    restart: always
    ports:
      - '5432:5432'
  server: 
    container_name: spbsrv
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
    env_file: .env.local
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    ports: 
      - 4005:4005
    depends_on:
      - postgres
    networks:
      - proxy
      - internal
volumes:
  postgres:
    driver: local
networks:
  proxy:
    name: revProxy
  internal: