version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: spbdb00
    restart: always
    ports:
      - '5432:5432'
    networks:
      - internal
  server: 
    container_name: spbsrv
    hostname: spbsrv
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - DISABLE_ERP=${DISABLE_ERP}
    ports: 
      - ${PORT}
    networks:
      - proxy
      - internal
  nginx:
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - proxy
    depends_on:
      - server
networks:
  proxy:
    name: revProxy
  internal:

    