version: '3.8'
services:
  nginx:
    hostname: nginx
    restart: unless-stopped
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - spbsrv
    networks:
      - proxynet
  postgres:
    hostname: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: spbdb00
    restart: always
    ports:
      - '5432:5432'
    networks:
      - external
  spbsrv: 
    hostname: spbsrv
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    ports: 
      - "4005"
    networks:
      - proxynet
      - external
    depends_on:
      - postgres
networks:
  proxynet:
    name: custom_network
  external:
     