version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: spbdb00
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
  server: 
    container_name: spbadm
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './:/app'
    env_file: .env.local
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    ports: 
      - 4005:4005
    depends_on:
      - postgres
volumes:
  postgres:
    driver: local